Better messages for stalker when person nick is unique
pingwindyktator/pybot pull request #8
Opened 2019-01-13 20:49 UTC by daniel1302

2019-01-14 14:25 UTC, pingwindyktator commented on plugins/stalker.py
> +        removed_nick = False
I dont like the idea of introducing additional variable here. I bet there are more straightforward ways to do this.

2019-01-14 14:26 UTC, pingwindyktator commented on plugins/stalker.py
> +            msgs = ['Gods believe, that %s is unique in our world.', 'We have seen %s lately.', '%s does not have multi accounts :(', ]
I would like to have one, specific answer in that case. "I don't know other %s nicks" maybe?

2019-01-14 14:26 UTC, pingwindyktator requested changes
Please see line comments.

2019-01-19 20:45 UTC, daniel1302 commented
@pingwindyktator I updated the code :)

2019-01-21 14:06 UTC, pingwindyktator approved these changes

2019-01-21 14:07 UTC, merged